apiVersion: v1
kind: Namespace
metadata:
  name: new-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application-deployment
  namespace: new-namespace
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: blurrysignature/web_application:v1.1
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-application-service
  namespace: new-namespace
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
